# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  config.vm.provision "shell", inline: <<-SHELL
    cat ../publickey/banzai-ko.pub >> /home/vagrant/.ssh/authorized_keys
  SHELL
  # Select the OS box
  config.vm.box = "ubuntu/jammy64"

  # Sync the folder
  config.vm.synced_folder '.', '/home/vagrant/foo'

  # Set hostname
  config.vm.hostname = "VmManagedNode"
  
  # Define the VM
  config.vm.define :VMPruebas do |t|
    # Add VM-specific settings here if needed
  end

  # Network settings
  config.vm.network "private_network", ip: "192.168.56.9"
  config.vm.network "forwarded_port", guest: 22, host: 8023
  config.vm.network "forwarded_port", guest: 80, host: 8080

 # config.vm.disk :disk, size: "10GB", name: "extra_storage"
 # config.vm.disk :disk, size: "10GB", name: "extra_storage2"

  # Provider-specific settings
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.name = "VmManagedNode"
    vb.cpus = 2
    vb.linked_clone = true
  end

end

